<?php

namespace App\Filament\Resources\PpdbRegistrations\Schemas;

use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\Select;
use Filament\Schemas\Schema;

class PpdbRegistrationForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('registration_number')
                    ->required()
                    ->disabled() // Typically generated by system, not edited directly
                    ->dehydrated(),
                TextInput::make('full_name')
                    ->required()
                    ->maxLength(255),
                TextInput::make('nisn')
                    ->required()
                    ->length(10)
                    ->unique(ignoreRecord: true),
                TextInput::make('email')
                    ->label('Email Address')
                    ->email()
                    ->required()
                    ->unique(ignoreRecord: true),
                TextInput::make('whatsapp_number')
                    ->required()
                    ->placeholder('e.g., 08123456789'),
                Select::make('major_priority_1')
                    ->relationship('major1', 'name')
                    ->required()
                    ->label('Pilihan Jurusan 1'),
                Select::make('major_priority_2')
                    ->relationship('major2', 'name')
                    ->required()
                    ->label('Pilihan Jurusan 2'),
                Select::make('status')
                    ->options([
                        'draft' => 'Draft',
                        'submitted' => 'Submitted',
                        'verified' => 'Verified',
                        'rejected' => 'Rejected',
                        'accepted' => 'Accepted',
                    ])
                    ->required()
                    ->default('draft')
                    ->native(false),
                Textarea::make('rejection_reason')
                    ->label('Alasan Penolakan')
                    ->columnSpanFull()
                    ->visible(fn ($get) => $get('status') === 'rejected'),
                DateTimePicker::make('submitted_at'),
            ]);
    }
}
